logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    com.java.brand: DEBUG

spring:
  profiles:
    active: dev
    include:
      - swagger
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      #uri: ${SPRING_DATA_MONGODB_URI}
      host: localhost
      port: 27017
      database: Brand #${SPRING_DATA_MONGODB_DATABASE}
      auto-index-creation: false
server:
  port: 8080