spring:
  application:
    name: Brand
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
server:
  servlet:
    session:
      cookie:
        http-only: true


jhipster:
  clientApp:
    name: 'Brand App'
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  swagger:
    default-include-pattern: /api/.*
    title: Brand API
    description: Brand API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name: Rizwan Iftikhar
    contact-url:
    contact-email: raorizwaniftikhar@gmail.com
    license:
    license-url:
