apiVersion: apps/v1
kind: Deployment
metadata:
  name: brand
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brand
      version: 'v1'
  template:
    metadata:
      labels:
        app: brand
        version: 'v1'
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - brand
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: init-ds
          image: busybox:latest
          command:
            - '/bin/sh'
            - '-c'
            - |
              while true
              do
                rt=$(nc -z -w 1 brand-mongodb 27017)
                if [ $? -eq 0 ]; then
                  echo "DB is UP"
                  break
                fi
                echo "DB is not yet reachable;sleep for 10s before retry"
                sleep 10
              done
      containers:
        - name: brand-app
          image: raorizwaniftikhar/brand
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev,swagger,tls
            - name: SPRING_DATA_MONGODB_DATABASE
              value: Brand
            - name: SPRING_DATA_MONGODB_URI
              value: 'mongodb://brand-mongodb-0.brand-mongodb.default:27017,brand-mongodb-1.brand-mongodb.default:27017,brand-mongodb-2.brand-mongodb.default:27017'
            - name: JAVA_OPTS
              value: ' -Xmx256m -Xms256m'
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
          ports:
            - name: http
              containerPort: 8080
       
