apiVersion: v1
kind: Service
metadata:
  name: brand
  namespace: default
  labels:
    app: brand
spec:
  selector:
    app: brand
  type: NodePort
  ports:
    - name: http
    # - protocol: TCP
      port: 80
      # nodePort: 30430
      targetPort: 8080
